spring:
     view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
     datasource:
        dataSourceClassName: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password: 
     jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
twilio:
    account_sid: asdfasdf
    auth_token: asdfadf

    


