spring:
     view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
     datasource:
        dataSourceClassName: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password: 

     jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: 
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true   
twilio:
    account_sid: ACc33504008109aa3d3cf5e329cc3dfe2e
    auth_token: 7ce54131d9446ae413141fd4014d2c91

    


